### ISSUE TITLE
How to build Thumos14reduced-annotations with my own data?

### ISSUE THREAD

**Issue by dztyykxx** [Run542968/ProCL#1]
First of all, thank you for your great work, this project is very rewarding. I wanted to ask how these annotation files were generated, I searched for a while, and I didn't find any instructions.
At the moment, I can use I3D to come up with the rgb and flow features of my own video and stitch them together to get a file like Thumos14reduced-I3D-JOINTFeatures.npy.
However, the time range of each video in segments.npy is annotated, Ambiguous_test.txt, how extracted_fps.npy got it still can't be understood, so I'm here to ask you for help.

**Comment by Run542968** [comment]
Thank you for your interest in our work. We follow HAM-Net and use the same annotation files, which you can find and download in [`their repository`](https://github.com/asrafulashiq/hamnet) -> [`file link`](https://rpi.app.box.com/s/hf6djlgs7vnl7a2oamjt0vkrig42pwho).

**Comment by Run542968** [comment]
I don't understand what your confusion is about this statement `"However, the time range of each video in segments.npy is annotated, Ambiguous_test.txt, how extracted_fps.npy got it still can't be understood, so I'm here to ask you for help."`. 

1. I'm guessing you're not sure how `fps` is obtained. Actually, this information can be obtained when extracting video frames using `ffmpeg`. This requires you to first download the original video from the dataset official website.
2. For `Ambiguous.txt` file and `segments annotation file`, you can find the annotations in the dataset's official website. [Thumos](https://www.crcv.ucf.edu/THUMOS14/download.html) and [AcitivityNet](http://activity-net.org/download.html).

Hope this answers your questions.
Best regards.
